################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
SREC := 
S_UPPER_DEPS := 
MAP := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/arm/CMSIS-DSP/Source/BasicMathFunctions \
ra/arm/CMSIS-DSP/Source/BayesFunctions \
ra/arm/CMSIS-DSP/Source/CommonTables \
ra/arm/CMSIS-DSP/Source/ComplexMathFunctions \
ra/arm/CMSIS-DSP/Source/ControllerFunctions \
ra/arm/CMSIS-DSP/Source/DistanceFunctions \
ra/arm/CMSIS-DSP/Source/FastMathFunctions \
ra/arm/CMSIS-DSP/Source/FilteringFunctions \
ra/arm/CMSIS-DSP/Source/InterpolationFunctions \
ra/arm/CMSIS-DSP/Source/MatrixFunctions \
ra/arm/CMSIS-DSP/Source/QuaternionMathFunctions \
ra/arm/CMSIS-DSP/Source/SVMFunctions \
ra/arm/CMSIS-DSP/Source/StatisticsFunctions \
ra/arm/CMSIS-DSP/Source/SupportFunctions \
ra/arm/CMSIS-DSP/Source/TransformFunctions \
ra/arm/CMSIS-DSP/Source/WindowFunctions \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/bsp/mcu/ra6m5 \
ra/fsp/src/r_dmac \
ra/fsp/src/r_gpt \
ra/fsp/src/r_ioport \
ra/fsp/src/r_rtc \
ra/fsp/src/r_sci_uart \
ra/fsp/src/r_sdhi \
ra/fsp/src/r_spi \
ra/fsp/src/rm_comms_lock \
ra/fsp/src/rm_comms_uart \
ra/fsp/src/rm_rai_data_collector \
ra/fsp/src/rm_rai_data_shipper \
ra_gen \
src/FatFs/ff15 \
src/Net/MQTT \
src/Net/cJSON \
src/Net/device \
src/Net/onenet \
src/RTC \
src/SD \
src/SEGGER_RTT \
src/applications \
src/debug_uart \
src/devices/ADXL345 \
src/devices/DHT11 \
src/devices \
src/drivers \
src \
src/key \
src/led \
src/libs/delay \
src/libs/ring_buffer \
src/rai \

