/* Code provided by Reality AI */
/* 
    Generated by Reality AI Tools
    Date            : 02/02/2026, 04:53:51
    Account         : xupt2951404774
    Project         : ADLX345
    Trained Tool    : amr_512_50_CSV_1 1.0
    H2Go Version    : 1.10
    Hopper Version  : 1.576
    Target          : RA6M5 (ARM Cortex-M33)
    Model Type      : RAI_SVM_CLASSIFIER
    User Data Type  : float32
    Window Length   : 512
    Channel Count   : 3
    Class Map       : [no_results: 0, DROP: 1, MOVE: 2, NORMAL: 3]
    ET Segmentation : None
    Smoothing       : None

    Copyright (c) Renesas of America, Inc.  All rights reserved.
    Use and distribution are subject to applicable contract restrictions.
*/

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef amr_MODEL_H
#define amr_MODEL_H

#include <stdlib.h>
#include "RealityAI.h"
#include "RealityAI_Config.h"
#include "RealityAI_Types.h"
#ifdef __cplusplus
extern "C" {
#endif

#define amr_FEATURENAME           "B2A5"
#define amr_NUM_CLASSES           3
#define amr_NUM_CHANNELS          3
#define amr_SAMPLES_PER_CHANNEL   512
#define amr_NUM_LEARNERS          3
#define amr_FEATURE_LENGTH        39
#define amr_USER_TYPE             float
#define amr_SAMPLES_PER_FRAME     (amr_SAMPLES_PER_CHANNEL * amr_NUM_CHANNELS)

typedef enum amr_AICLASS{
	amr_no_results=0,
	amr_DROP=1,
	amr_MOVE=2,
	amr_NORMAL=3
} amr_AICLASS;

struct rai_model_struct* get_amr_model(void);
amr_AICLASS amr_predict(float* inputData);

#ifdef __cplusplus
}
#endif
#endif /* amr_MODEL_H */

