/* Code provided by Reality AI */
/* 
    Generated by Reality AI Tools
    Date            : 02/02/2026, 04:53:51
    Account         : xupt2951404774
    Project         : ADLX345
    Trained Tool    : amr_512_50_CSV_1 1.0
    H2Go Version    : 1.10
    Hopper Version  : 1.576
    Target          : RA6M5 (ARM Cortex-M33)
    Model Type      : RAI_SVM_CLASSIFIER
    User Data Type  : float32
    Window Length   : 512
    Channel Count   : 3
    Class Map       : [no_results: 0, DROP: 1, MOVE: 2, NORMAL: 3]
    ET Segmentation : None
    Smoothing       : None

    Copyright (c) Renesas of America, Inc.  All rights reserved.
    Use and distribution are subject to applicable contract restrictions.
*/

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <stdio.h>
#include "amr_model.h"
#ifdef __linux__
#include <unistd.h>
#endif

int example_main(void);

#define APPLY_SOFTMAX  1
static float conf_scores[amr_NUM_CLASSES];  /* confidence scores */
static float inputData[amr_SAMPLES_PER_CHANNEL * amr_NUM_CHANNELS];

int example_main(void)
{
    /* Init Your board and hardware here. */

    /* Example code loop
    *  Enter an infinite loop, generate a random vector of input data, execute predict function,
    *  and print the result. Replace this with your actual data read and windowing process.
    */

    while(1){
        /*
         * Fetch next data input window from your device.
         * Sensor data is simulated in this loop and formatted as a single dimensional array in WC
         * format (width W, channels C). Multi-channel windows are constructed for single-event prediction.
         *
         * Expected format of sensor data stream:
         * ch0[0],ch0[1],...,ch0[N-1], ch1[0],ch1[1],...,ch1[N-1], ... where N is SAMPLES_PER_CHANNEL (Window Length)
         * REPLACE THIS BLOCK WITH INPUT FROM YOUR DEVICE
        */
        for(size_t sample = 0; sample < amr_SAMPLES_PER_CHANNEL; sample++){
            for(size_t channel = 0; channel < amr_NUM_CHANNELS; channel++){
                float x = (float)((rand() % 64000) - 32000);
                inputData[channel*amr_SAMPLES_PER_CHANNEL+sample] = x;
            }
        }
    
        /* Model prediction */
        amr_AICLASS AIC = amr_predict(inputData);
        
        /* Convert class score to confidence score (CS) */
        RealityAI_get_class_scores(conf_scores, amr_NUM_CLASSES, APPLY_SOFTMAX, get_amr_model());

        /* Decode classification event using class names */
		switch(AIC){
		case(amr_no_results):
			printf("Predicted Class: no_results\n");
			break;
		case(amr_DROP):
			printf("Predicted Class: DROP [%.2f]\n", conf_scores[0]);
			break;
		case(amr_MOVE):
			printf("Predicted Class: MOVE [%.2f]\n", conf_scores[1]);
			break;
		case(amr_NORMAL):
			printf("Predicted Class: NORMAL [%.2f]\n", conf_scores[2]);
			break;
		};

        /* throttle execution speed */
    #ifdef __linux__
        sleep(1);
    #endif
  }
  return 0;
}
