/* Code provided by Reality AI */
/* 
    Generated by Reality AI Tools
<<<<<<< HEAD
    Date            : 03/27/2026, 22:16:42
    Account         : xupt2951404774
    Project         : Renesas_Cup_Release_2026_3_28_Final
    Trained Tool    : single_list_2_1 1.0
    H2Go Version    : 1.11
    Hopper Version  : 0.0.0
    Target          : RA6M5 (ARM Cortex-M33)
    Model Type      : RAI_NEURAL_CLASSIFIER
    User Data Type  : float32
    Window Length   : 512
    Channel Count   : 6
    Class Map       : [no_results: 0, motor_base_fault_level_high: 1, motor_base_fault_level_low: 2, motor_base_fault_level_medium: 3, motor_runnnig_fan: 4, motor_runnnig_fan_unbalance: 5, motor_stop: 6]
    ET Segmentation : None
    Smoothing       : None

    Copyright (c) Renesas of America, Inc.  All rights reserved.
    Use and distribution are subject to applicable contract restrictions.
*/

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <stdio.h>
#include "Motor_Monitor_NN_model.h"
#ifdef __linux__
#include <unistd.h>
#endif

int example_main(void);

#define APPLY_SOFTMAX  1
static float scores[Motor_Monitor_NN_NUM_CLASSES];  /* confidence scores */
static float inputData[Motor_Monitor_NN_SAMPLES_PER_CHANNEL * Motor_Monitor_NN_NUM_CHANNELS];

int example_main(void)
{
    /* Init Your board and hardware here. */

    /* Example code loop
    *  Enter an infinite loop, generate a random vector of input data, execute predict function,
    *  and print the result. Replace this with your actual data read and windowing process.
    */

    while(1){
        /*
         * Fetch next data input window from your device.
         * Sensor data is simulated in this loop and formatted as a single dimensional array in WC
         * format (width W, channels C). Multi-channel windows are constructed for single-event prediction.
         *
         * Expected format of sensor data stream:
         * ch0[0],ch0[1],...,ch0[N-1], ch1[0],ch1[1],...,ch1[N-1], ... where N is SAMPLES_PER_CHANNEL (Window Length)
         * REPLACE THIS BLOCK WITH INPUT FROM YOUR DEVICE
        */
        for(size_t sample = 0; sample < Motor_Monitor_NN_SAMPLES_PER_CHANNEL; sample++){
            for(size_t channel = 0; channel < Motor_Monitor_NN_NUM_CHANNELS; channel++){
                float x = (float)((rand() % 64000) - 32000);
                inputData[channel*Motor_Monitor_NN_SAMPLES_PER_CHANNEL+sample] = x;
            }
        }
    
        /* Model prediction */
        Motor_Monitor_NN_AICLASS AIC = Motor_Monitor_NN_predict(inputData);
        
        /* Convert class score to confidence score (CS) */
        RealityAI_get_class_scores(scores, Motor_Monitor_NN_NUM_CLASSES, APPLY_SOFTMAX, get_Motor_Monitor_NN_model());

        /* Decode classification event using class names */
		switch(AIC){
		case(Motor_Monitor_NN_no_results):
			printf("Predicted Class: no_results\n");
			break;
		case(Motor_Monitor_NN_motor_base_fault_level_high):
			printf("Predicted Class: motor_base_fault_level_high, Score: %.3f\n", scores[(int)AIC-1]);
			break;
		case(Motor_Monitor_NN_motor_base_fault_level_low):
			printf("Predicted Class: motor_base_fault_level_low, Score: %.3f\n", scores[(int)AIC-1]);
			break;
		case(Motor_Monitor_NN_motor_base_fault_level_medium):
			printf("Predicted Class: motor_base_fault_level_medium, Score: %.3f\n", scores[(int)AIC-1]);
			break;
		case(Motor_Monitor_NN_motor_runnnig_fan):
			printf("Predicted Class: motor_runnnig_fan, Score: %.3f\n", scores[(int)AIC-1]);
			break;
		case(Motor_Monitor_NN_motor_runnnig_fan_unbalance):
			printf("Predicted Class: motor_runnnig_fan_unbalance, Score: %.3f\n", scores[(int)AIC-1]);
			break;
		case(Motor_Monitor_NN_motor_stop):
			printf("Predicted Class: motor_stop, Score: %.3f\n", scores[(int)AIC-1]);
=======
    Date            : 02/03/2026, 14:11:05
    Account         : xupt2951404774
    Project         : Renesas_Cup
    Trained Tool    : Motor_monitor_1 1.0
    H2Go Version    : 1.10
    Hopper Version  : 0.0.0
    Target          : RA6M5 (ARM Cortex-M33)
    Model Type      : RAI_NEURAL_CLASSIFIER
    User Data Type  : float32
    Window Length   : 512
    Channel Count   : 3
    Class Map       : [no_results: 0, base_loose_state: 1, idle_state: 2, load_worse_state: 3, run_state: 4]
    ET Segmentation : None
    Smoothing       : None

    Copyright (c) Renesas of America, Inc.  All rights reserved.
    Use and distribution are subject to applicable contract restrictions.
*/

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <stdio.h>
#include "Motor_monitor_1_model.h"
#ifdef __linux__
#include <unistd.h>
#endif

int example_main(void);

#define APPLY_SOFTMAX  1
static float conf_scores[Motor_monitor_1_NUM_CLASSES];  /* confidence scores */
static float inputData[Motor_monitor_1_SAMPLES_PER_CHANNEL * Motor_monitor_1_NUM_CHANNELS];

int example_main(void)
{
    /* Init Your board and hardware here. */

    /* Example code loop
    *  Enter an infinite loop, generate a random vector of input data, execute predict function,
    *  and print the result. Replace this with your actual data read and windowing process.
    */

    while(1){
        /*
         * Fetch next data input window from your device.
         * Sensor data is simulated in this loop and formatted as a single dimensional array in WC
         * format (width W, channels C). Multi-channel windows are constructed for single-event prediction.
         *
         * Expected format of sensor data stream:
         * ch0[0],ch0[1],...,ch0[N-1], ch1[0],ch1[1],...,ch1[N-1], ... where N is SAMPLES_PER_CHANNEL (Window Length)
         * REPLACE THIS BLOCK WITH INPUT FROM YOUR DEVICE
        */
        for(size_t sample = 0; sample < Motor_monitor_1_SAMPLES_PER_CHANNEL; sample++){
            for(size_t channel = 0; channel < Motor_monitor_1_NUM_CHANNELS; channel++){
                float x = (float)((rand() % 64000) - 32000);
                inputData[channel*Motor_monitor_1_SAMPLES_PER_CHANNEL+sample] = x;
            }
        }
    
        /* Model prediction */
        Motor_monitor_1_AICLASS AIC = Motor_monitor_1_predict(inputData);
        
        /* Convert class score to confidence score (CS) */
        RealityAI_get_class_scores(conf_scores, Motor_monitor_1_NUM_CLASSES, APPLY_SOFTMAX, get_Motor_monitor_1_model());

        /* Decode classification event using class names */
		switch(AIC){
		case(Motor_monitor_1_no_results):
			printf("Predicted Class: no_results\n");
			break;
		case(Motor_monitor_1_base_loose_state):
			printf("Predicted Class: base_loose_state [%.2f]\n", conf_scores[0]);
			break;
		case(Motor_monitor_1_idle_state):
			printf("Predicted Class: idle_state [%.2f]\n", conf_scores[1]);
			break;
		case(Motor_monitor_1_load_worse_state):
			printf("Predicted Class: load_worse_state [%.2f]\n", conf_scores[2]);
			break;
		case(Motor_monitor_1_run_state):
			printf("Predicted Class: run_state [%.2f]\n", conf_scores[3]);
>>>>>>> branch 'main' of git@github.com:Wendellee/Embedded-Competition-Renesas-Track.git
			break;
		};

        /* throttle execution speed */
    #ifdef __linux__
        sleep(1);
    #endif
  }
  return 0;
}
