/* Code provided by Reality AI */
/* 
    Generated by Reality AI Tools
    Date            : 03/27/2026, 22:16:42
    Account         : xupt2951404774
    Project         : Renesas_Cup_Release_2026_3_28_Final
    Trained Tool    : single_list_2_1 1.0
    H2Go Version    : 1.11
    Hopper Version  : 0.0.0
    Target          : RA6M5 (ARM Cortex-M33)
    Model Type      : RAI_NEURAL_CLASSIFIER
    User Data Type  : float32
    Window Length   : 512
    Channel Count   : 6
    Class Map       : [no_results: 0, motor_base_fault_level_high: 1, motor_base_fault_level_low: 2, motor_base_fault_level_medium: 3, motor_runnnig_fan: 4, motor_runnnig_fan_unbalance: 5, motor_stop: 6]
    ET Segmentation : None
    Smoothing       : None

    Copyright (c) Renesas of America, Inc.  All rights reserved.
    Use and distribution are subject to applicable contract restrictions.
*/

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef Motor_Monitor_NN_MODEL_H
#define Motor_Monitor_NN_MODEL_H

#include <stdlib.h>
#include "RealityAI.h"
#include "RealityAI_Config.h"
#include "RealityAI_Types.h"
#ifdef __cplusplus
extern "C" {
#endif

#define Motor_Monitor_NN_FEATURENAME           "C1"
#define Motor_Monitor_NN_NUM_CLASSES           6
#define Motor_Monitor_NN_NUM_CHANNELS          6
#define Motor_Monitor_NN_SAMPLES_PER_CHANNEL   512
#define Motor_Monitor_NN_NUM_LEARNERS          1
#define Motor_Monitor_NN_FEATURE_LENGTH        1536
#define Motor_Monitor_NN_USER_TYPE             float
#define Motor_Monitor_NN_SAMPLES_PER_FRAME     (Motor_Monitor_NN_SAMPLES_PER_CHANNEL * Motor_Monitor_NN_NUM_CHANNELS)

typedef enum Motor_Monitor_NN_AICLASS{
	Motor_Monitor_NN_no_results=0,
	Motor_Monitor_NN_motor_base_fault_level_high=1,
	Motor_Monitor_NN_motor_base_fault_level_low=2,
	Motor_Monitor_NN_motor_base_fault_level_medium=3,
	Motor_Monitor_NN_motor_runnnig_fan=4,
	Motor_Monitor_NN_motor_runnnig_fan_unbalance=5,
	Motor_Monitor_NN_motor_stop=6
} Motor_Monitor_NN_AICLASS;

struct rai_model_struct* get_Motor_Monitor_NN_model(void);
Motor_Monitor_NN_AICLASS Motor_Monitor_NN_predict(float* inputData);

#ifdef __cplusplus
}
#endif
#endif /* Motor_Monitor_NN_MODEL_H */

