/* Code provided by Reality AI */
/* 
    Generated by Reality AI Tools
    Date            : 02/03/2026, 14:11:05
    Account         : xupt2951404774
    Project         : Renesas_Cup
    Trained Tool    : Motor_monitor_1 1.0
    H2Go Version    : 1.10
    Hopper Version  : 0.0.0
    Target          : RA6M5 (ARM Cortex-M33)
    Model Type      : RAI_NEURAL_CLASSIFIER
    User Data Type  : float32
    Window Length   : 512
    Channel Count   : 3
    Class Map       : [no_results: 0, base_loose_state: 1, idle_state: 2, load_worse_state: 3, run_state: 4]
    ET Segmentation : None
    Smoothing       : None

    Copyright (c) Renesas of America, Inc.  All rights reserved.
    Use and distribution are subject to applicable contract restrictions.
*/

/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef Motor_monitor_1_MODEL_H
#define Motor_monitor_1_MODEL_H

#include <stdlib.h>
#include "RealityAI.h"
#include "RealityAI_Config.h"
#include "RealityAI_Types.h"
#ifdef __cplusplus
extern "C" {
#endif

#define Motor_monitor_1_FEATURENAME           "C1"
#define Motor_monitor_1_NUM_CLASSES           4
#define Motor_monitor_1_NUM_CHANNELS          3
#define Motor_monitor_1_SAMPLES_PER_CHANNEL   512
#define Motor_monitor_1_NUM_LEARNERS          1
#define Motor_monitor_1_FEATURE_LENGTH        768
#define Motor_monitor_1_USER_TYPE             float
#define Motor_monitor_1_SAMPLES_PER_FRAME     (Motor_monitor_1_SAMPLES_PER_CHANNEL * Motor_monitor_1_NUM_CHANNELS)

typedef enum Motor_monitor_1_AICLASS{
	Motor_monitor_1_no_results=0,
	Motor_monitor_1_base_loose_state=1,
	Motor_monitor_1_idle_state=2,
	Motor_monitor_1_load_worse_state=3,
	Motor_monitor_1_run_state=4
} Motor_monitor_1_AICLASS;

struct rai_model_struct* get_Motor_monitor_1_model(void);
Motor_monitor_1_AICLASS Motor_monitor_1_predict(float* inputData);

#ifdef __cplusplus
}
#endif
#endif /* Motor_monitor_1_MODEL_H */

