#include "hal_data.h"
#include "app_led.h"
#include "app_key.h"
#include "debug_uart.h"
#include <stdio.h>
#include <stdarg.h>
#include "stdio.h"
#include "app.h"
#include "common_utils.h"


#include "devices.h"
#include "libs.h"
#include "errno.h"

// 在头文件包含部分添加：
#include "rm_rai_data_collector.h"  // RAI数据采集器头文件
#include "rm_rai_data_shipper.h"    // RAI数据发送器头文件

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

#define DATA_COLLECTION_EN       (1)         //收集数据时打开

#define ADLX345_SELF_TEST_EN   (1)         //ADXL345自检程序
#define MAINTENAION_TEST_EN    (0)         //主控板自检程序

#define  NUM_BUFFS 2
#define WINDOW_SIZE (512)
#define BUFF_LEN (WINDOW_SIZE)

#define SMOOTH_LEN 5

static int count = 0;
float data_x[BUFF_LEN];
float data_y[BUFF_LEN];
float data_z[BUFF_LEN];

static uint16_t g_events = 0;
static uint32_t g_err_count = 0;
static bool g_dc_callback = false;
static rai_data_collector_callback_args_t g_callback_args;
rai_data_collector_frame_buffer_t g_frame_buf[8];
#if DATA_COLLECTION_EN==0
#include "Motor_monitor_1_model.h"

static float inputData[Motor_monitor_1_SAMPLES_PER_CHANNEL * Motor_monitor_1_NUM_CHANNELS];
Motor_monitor_1_AICLASS AIC;
#endif

void rai_data_collector_error_callback(const rai_data_collector_error_callback_args_t *p_args);

void rai_data_collector0_callback(const rai_data_collector_callback_args_t *p_args)
{
    g_callback_args.frame_buf_len = p_args->frame_buf_len;
    g_callback_args.frames = p_args->frames;
    g_callback_args.instance_id = p_args->instance_id;
    for(uint8_t i = 0; i < p_args->frames; i++)
    {
        g_frame_buf[i] = p_args->p_frame_buf[i];
    }
    g_callback_args.p_frame_buf = g_frame_buf;

    g_dc_callback = true;
}

void rai_data_collector0_error_callback(const rai_data_collector_error_callback_args_t *p_args)
{
    g_events |= p_args->event;
}

void rai_data_collector_error_callback(const rai_data_collector_error_callback_args_t *p_args)
{
    g_events |= p_args->event;
}

void rai_data_shipper0_callback(rai_data_shipper_callback_args_t *p_args)
{
    if(p_args->result != (uint16_t)FSP_SUCCESS)
    {
        g_err_count++;
    }
    g_rai_data_collector0.p_api->bufferRelease(&g_rai_data_collector0_ctrl);
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    debug_uart7_init();
    hmi_uart9_init();
    Serial_Printf(g_uart7.p_ctrl,"This is RA6M5's here!\r\n");

    TimerDevicesRegister();
    SPIDevicesRegister();
    IODevicesRegister();

    ADXL345Device *pADXL345 = ADXL345GetDevice();
    if(NULL == pADXL345)
    {
        xprintf("Failed to Find ADXL345 Device!\r\n");
        return;
    }
    pADXL345->Init(pADXL345);

 #if DATA_COLLECTION_EN
    RM_RAI_DATA_COLLECTOR_Open(&g_rai_data_collector0_ctrl, &g_rai_data_collector0_cfg);
    RM_RAI_DATA_SHIPPER_Open(&g_rai_data_shipper0_ctrl, &g_rai_data_shipper0_cfg);

    RM_RAI_DATA_COLLECTOR_BufferReset(&g_rai_data_collector0_ctrl);

    RM_RAI_DATA_COLLECTOR_ChannelBufferGet(&g_rai_data_collector0_ctrl, 0, (void*)data_x);
    RM_RAI_DATA_COLLECTOR_ChannelBufferGet(&g_rai_data_collector0_ctrl, 1, (void*)data_y);
    RM_RAI_DATA_COLLECTOR_ChannelBufferGet(&g_rai_data_collector0_ctrl, 2, (void*)data_z);
#endif



#if ADLX345_SELF_TEST_EN
    while(1)
    {   //获取数据
        if(pADXL345->Read(pADXL345) == ESUCCESS)
        {
//            xprintf("x:%.4fg\ty:%.4fg\tz:%.4fg\r\n", pADXL345->value.x, pADXL345->value.y, pADXL345->value.z);
            xprintf("add s0.id,0,%d\xff\xff\xff",(uint16_t)((pADXL345->value.x *50 / 8)+ 50));
            xprintf("add s2.id,0,%d\xff\xff\xff",(uint16_t)((pADXL345->value.y *50 / 8)+ 50));
            xprintf("add s1.id,0,%d\xff\xff\xff",(uint16_t)((pADXL345->value.z *50 / 8)+ 50));
            if(count < BUFF_LEN){
            //收集数据
            data_x[count] = pADXL345->value.x;
            data_y[count] = pADXL345->value.y;
            data_z[count] = pADXL345->value.z;


            #if DATA_COLLECTION_EN==0
            inputData[count] = pADXL345->value.x;
            inputData[count+WINDOW_SIZE] = pADXL345->value.y;
            inputData[count+2*WINDOW_SIZE] = pADXL345->value.z;
            #endif
            count++;
            }
            else{
                #if DATA_COLLECTION_EN
                RM_RAI_DATA_COLLECTOR_ChannelWrite(&g_rai_data_collector0_ctrl, 0, data_x, BUFF_LEN);
                RM_RAI_DATA_COLLECTOR_ChannelWrite(&g_rai_data_collector0_ctrl, 1, data_y, BUFF_LEN);
                RM_RAI_DATA_COLLECTOR_ChannelWrite(&g_rai_data_collector0_ctrl, 2, data_z, BUFF_LEN);

                rai_data_shipper_write_params_t arg;
                arg.diagnostic_data_len = 0;
                arg.events = g_events;
                arg.p_diagnostic_data = NULL;
                arg.p_sensor_data = &g_callback_args;
                g_dc_callback = false;

                RM_RAI_DATA_SHIPPER_Write(&g_rai_data_shipper0_ctrl, &arg);
                g_dc_callback = false;
                #else
                //模型推理
                /* Model prediction */
                Motor_monitor_1_AICLASS AIC = Motor_monitor_1_predict(inputData);
                /* Decode classification event using class names */
                switch(AIC){
                case(Motor_monitor_1_no_results):
                    xprintf("t15.txt=\"None\"\xff\xff\xff");
                break;
                case(Motor_monitor_1_base_loose_state):
                    xprintf("t15.txt=\"base\"\xff\xff\xff");
                break;
                case(Motor_monitor_1_idle_state):
                    xprintf("t15.txt=\"idle\"\xff\xff\xff");
                break;
                case(Motor_monitor_1_load_worse_state):
                    xprintf("t15.txt=\"load\"\xff\xff\xff");
                break;
                case(Motor_monitor_1_run_state):
                    xprintf("t15.txt=\"run\"\xff\xff\xff");
                break;
                };
            #endif
            count = 0;
            }
        }
        mdelay(5);
    }
#endif

#if MAINTENAION_TEST_EN
    while(1)
    {
//        ds_led_blink(150);
//        Serial_Printf(g_uart7.p_ctrl,"This is RA6M5's here!\r\n");


    }

#endif



void hmi(void)
{
    
}


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
